FROM golang:1.22.2

RUN mkdir /app
WORKDIR /app

COPY . .

RUN go get -u github.com/gin-gonic/gin
RUN go get -u github.com/gin-contrib/cors
RUN go get -u github.com/mattn/go-sqlite3

EXPOSE 8080

CMD ["go", "run", "."]